#pragma once

struct JCRECT
{
	float x;
	float y;
	float w;
	float h;
};


enum ActionList
{
	JCDINAMIC_EFFECT  = 1,
	JCSTATIC_EFFECT   = 2,
	JCSKILL_EFFECT    = 3,
	JCITEMGLOW_EFFECT = 4,
	JCOBJECTSHADOW    = 5,
	JCOBJECTWORLDHIDE = 6,
	JTWINGSOBJECT     = 7,  //ZEUS UP21 UPGRAND ANTLAG PAINEL
	JTWEAPONOBJECT    = 8,  //ZEUS UP21 UPGRAND ANTLAG PAINEL
	JTCLOACKOBJECT    = 9,  //ZEUS UP21 UPGRAND ANTLAG PAINEL
	JTPLAYEROBJECT    = 10, //ZEUS UP21 UPGRAND ANTLAG PAINEL
	NONE = 11,
	DEFAULT = 12,
};